version: '3.9'

services:

  purchase.api:
    container_name: purchase-api

    build:
      context: .
      dockerfile: src/Purchase.Api/Dockerfile

    ports:
      - "${PURCHASE_API_PORT}:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      MongoDbSettings__ConnectionString: mongodb://mongo:27017
      MongoDbSettings__DatabaseName: ${PURCHASE_DB_NAME}
      
      MongoDbSettings__PurchaseCollection: ${PURCHASE_DB_PURCHASE_COLLECTION}
      MongoDbSettings__OrderCollection: ${PURCHASE_DB_ORDER_COLLECTION}
      MongoDbSettings__OrderItemCollection: ${PURCHASE_DB_ORDER_ITEM_COLLECTION}

      Stripe__SecretKey: ${STRIPE_SECRET_KEY}

    depends_on:
      - mongo

    networks:
      - purchase-network

  mongo:
    image: mongo:7

    container_name: ${PURCHASE_CONTAINER_NAME}

    restart: always

    ports:
      - "${PURCHASE_DB_PORT}:27017"

    volumes:
      - mongo_data:/data/db

    networks:
      - purchase-network

volumes:
  mongo_data:

networks:
  purchase-network: