/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicPaymentSuccessRouteImport } from './routes/_public/payment-success'
import { Route as PublicPaymentCancelRouteImport } from './routes/_public/payment-cancel'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedMyListingRouteImport } from './routes/_protected/my-listing'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedCreateListingRouteImport } from './routes/_protected/create-listing'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/_admin/route'
import { Route as PublicCatalogueIndexRouteImport } from './routes/_public/catalogue/index'
import { Route as PublicCatalogueSalesPostGuidRouteImport } from './routes/_public/catalogue/$salesPostGuid'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/_admin/users'
import { Route as ProtectedAdminListingsRouteImport } from './routes/_protected/_admin/listings'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPaymentSuccessRoute = PublicPaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPaymentCancelRoute = PublicPaymentCancelRouteImport.update({
  id: '/payment-cancel',
  path: '/payment-cancel',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMyListingRoute = ProtectedMyListingRouteImport.update({
  id: '/my-listing',
  path: '/my-listing',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCreateListingRoute = ProtectedCreateListingRouteImport.update({
  id: '/create-listing',
  path: '/create-listing',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicCatalogueIndexRoute = PublicCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCatalogueSalesPostGuidRoute =
  PublicCatalogueSalesPostGuidRouteImport.update({
    id: '/catalogue/$salesPostGuid',
    path: '/catalogue/$salesPostGuid',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminListingsRoute = ProtectedAdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/create-listing': typeof ProtectedCreateListingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/my-listing': typeof ProtectedMyListingRoute
  '/profile': typeof ProtectedProfileRoute
  '/login': typeof PublicLoginRoute
  '/payment-cancel': typeof PublicPaymentCancelRoute
  '/payment-success': typeof PublicPaymentSuccessRoute
  '/register': typeof PublicRegisterRoute
  '/listings': typeof ProtectedAdminListingsRoute
  '/users': typeof ProtectedAdminUsersRoute
  '/catalogue/$salesPostGuid': typeof PublicCatalogueSalesPostGuidRoute
  '/catalogue/': typeof PublicCatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/create-listing': typeof ProtectedCreateListingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/my-listing': typeof ProtectedMyListingRoute
  '/profile': typeof ProtectedProfileRoute
  '/login': typeof PublicLoginRoute
  '/payment-cancel': typeof PublicPaymentCancelRoute
  '/payment-success': typeof PublicPaymentSuccessRoute
  '/register': typeof PublicRegisterRoute
  '/listings': typeof ProtectedAdminListingsRoute
  '/users': typeof ProtectedAdminUsersRoute
  '/catalogue/$salesPostGuid': typeof PublicCatalogueSalesPostGuidRoute
  '/catalogue': typeof PublicCatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_protected/_admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/create-listing': typeof ProtectedCreateListingRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/my-listing': typeof ProtectedMyListingRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/payment-cancel': typeof PublicPaymentCancelRoute
  '/_public/payment-success': typeof PublicPaymentSuccessRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/_admin/listings': typeof ProtectedAdminListingsRoute
  '/_protected/_admin/users': typeof ProtectedAdminUsersRoute
  '/_public/catalogue/$salesPostGuid': typeof PublicCatalogueSalesPostGuidRoute
  '/_public/catalogue/': typeof PublicCatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-listing'
    | '/dashboard'
    | '/my-listing'
    | '/profile'
    | '/login'
    | '/payment-cancel'
    | '/payment-success'
    | '/register'
    | '/listings'
    | '/users'
    | '/catalogue/$salesPostGuid'
    | '/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-listing'
    | '/dashboard'
    | '/my-listing'
    | '/profile'
    | '/login'
    | '/payment-cancel'
    | '/payment-success'
    | '/register'
    | '/listings'
    | '/users'
    | '/catalogue/$salesPostGuid'
    | '/catalogue'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_protected/_admin'
    | '/_protected/create-listing'
    | '/_protected/dashboard'
    | '/_protected/my-listing'
    | '/_protected/profile'
    | '/_public/login'
    | '/_public/payment-cancel'
    | '/_public/payment-success'
    | '/_public/register'
    | '/_public/'
    | '/_protected/_admin/listings'
    | '/_protected/_admin/users'
    | '/_public/catalogue/$salesPostGuid'
    | '/_public/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/payment-success': {
      id: '/_public/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PublicPaymentSuccessRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/payment-cancel': {
      id: '/_public/payment-cancel'
      path: '/payment-cancel'
      fullPath: '/payment-cancel'
      preLoaderRoute: typeof PublicPaymentCancelRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/my-listing': {
      id: '/_protected/my-listing'
      path: '/my-listing'
      fullPath: '/my-listing'
      preLoaderRoute: typeof ProtectedMyListingRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/create-listing': {
      id: '/_protected/create-listing'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof ProtectedCreateListingRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_admin': {
      id: '/_protected/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/catalogue/': {
      id: '/_public/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof PublicCatalogueIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/catalogue/$salesPostGuid': {
      id: '/_public/catalogue/$salesPostGuid'
      path: '/catalogue/$salesPostGuid'
      fullPath: '/catalogue/$salesPostGuid'
      preLoaderRoute: typeof PublicCatalogueSalesPostGuidRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/_admin/users': {
      id: '/_protected/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/_admin/listings': {
      id: '/_protected/_admin/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ProtectedAdminListingsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminListingsRoute: typeof ProtectedAdminListingsRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminListingsRoute: ProtectedAdminListingsRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedCreateListingRoute: typeof ProtectedCreateListingRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMyListingRoute: typeof ProtectedMyListingRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedCreateListingRoute: ProtectedCreateListingRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMyListingRoute: ProtectedMyListingRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicPaymentCancelRoute: typeof PublicPaymentCancelRoute
  PublicPaymentSuccessRoute: typeof PublicPaymentSuccessRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCatalogueSalesPostGuidRoute: typeof PublicCatalogueSalesPostGuidRoute
  PublicCatalogueIndexRoute: typeof PublicCatalogueIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicPaymentCancelRoute: PublicPaymentCancelRoute,
  PublicPaymentSuccessRoute: PublicPaymentSuccessRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCatalogueSalesPostGuidRoute: PublicCatalogueSalesPostGuidRoute,
  PublicCatalogueIndexRoute: PublicCatalogueIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
