/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginPageRouteImport } from './routes/login-page'
import { Route as BrowsePageRouteImport } from './routes/browse-page'
import { Route as IndexRouteImport } from './routes/index'

const LoginPageRoute = LoginPageRouteImport.update({
  id: '/login-page',
  path: '/login-page',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePageRoute = BrowsePageRouteImport.update({
  id: '/browse-page',
  path: '/browse-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse-page': typeof BrowsePageRoute
  '/login-page': typeof LoginPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse-page': typeof BrowsePageRoute
  '/login-page': typeof LoginPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse-page': typeof BrowsePageRoute
  '/login-page': typeof LoginPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browse-page' | '/login-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse-page' | '/login-page'
  id: '__root__' | '/' | '/browse-page' | '/login-page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowsePageRoute: typeof BrowsePageRoute
  LoginPageRoute: typeof LoginPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-page': {
      id: '/login-page'
      path: '/login-page'
      fullPath: '/login-page'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse-page': {
      id: '/browse-page'
      path: '/browse-page'
      fullPath: '/browse-page'
      preLoaderRoute: typeof BrowsePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowsePageRoute: BrowsePageRoute,
  LoginPageRoute: LoginPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
