services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  purchaseservice:
    build: ./services/purchase-service
    container_name: purchaseservice
    depends_on:
      - rabbitmq
      - mysql

  emailservice:
    build: ./services/email-service
    container_name: emailservice
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - MAILJET_API_KEY=${MAILJET_API_KEY}
      - MAILJET_SECRET=${MAILJET_SECRET}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MYSQL_CONNECTION=${MYSQL_EMAIL_CONNECTION}

  synchronizerservice:
    build: ./services/product-synchronizer
    container_name: synchronizerservice
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - MONGO_CONNECTION=${MONGO_CONNECTION}
      - QUEUE_NAME=${QUEUE_NAME}
      - MYSQL_CONNECTION=${MYSQL_SYNC_CONNECTION}

volumes:
  mysql_data: