
version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: furnitures
    volumes:
      - mongo_data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d
    networks:
      - backend
    restart: unless-stopped

  purchaseservice:
    build:
      context: .
      dockerfile: DockerFile
    container_name: purchaseservice
    ports:
      - "5258:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      QUEUE_NAME: listing_queue
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      MONGO_CONNECTION: mongodb://mongo:27017

    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  mongo_data: