services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  purchaseservice:
    build:
      context: .
      dockerfile: DockerFile
    container_name: purchaseservice
    ports:
      - "5001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      QUEUE_NAME: listing_queue
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

      STRIPE_API_KEY: pk_test_xxx
      STRIPE_SECRET_KEY: sk_test_xxx
      STRIPE_WEBHOOK_SECRET: whsec_xxx
    networks:
      - backend
    restart: unless-stopped

networks:
  backend: