package dk.iredo.product_storage.listings;

import dk.iredo.product_storage.categories.entities.Category;
import dk.iredo.product_storage.categories.entities.SubCategory;
import dk.iredo.product_storage.categories.repositories.CategoryRepository;
import dk.iredo.product_storage.categories.repositories.SubCategoryRepository;
import dk.iredo.product_storage.colors.Color;
import dk.iredo.product_storage.colors.ColorsRepository;
import dk.iredo.product_storage.listings.entities.enums.Condition;
import dk.iredo.product_storage.listings.entities.Listing;
import dk.iredo.product_storage.listings.repositories.ListingRepository;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@SpringBootTest
@TestPropertySource(
        locations = "classpath:testApplication.properties")
class ListingsServiceTest {

    @Autowired
    ColorsRepository colorsRepository;

    @Autowired
    CategoryRepository categoryRepository;

    @Autowired
    SubCategoryRepository subCategoryRepository;

    @Autowired
    ListingsService listingsService;

    @BeforeEach()
    void setup() {
        /*Examples*/
        //colorsRepository.save(new Color("White", "#ffffff"));
        //colorsRepository.save(new Color("Blue", "#2f4df7"));
        //colorsRepository.save(new Color("Green", "#2ff757"));

        //Category sofas = categoryRepository.save(new Category("Sofas"));
        //Category beds = categoryRepository.save(new Category("Beds"));
        //Category tables = categoryRepository.save(new Category("Tables"));


        //subCategories.add(new SubCategory("Lounge chair", chairs));
        //subCategories.add(new SubCategory("Modular sofa", sofas));
        //subCategories.add(new SubCategory("Dream bed", beds));
        //subCategories.add(new SubCategory("Dinner table", tables));
    }

    @Test
    void testAddingFullListing() {
        /*Arrange*/
        colorsRepository.save(new Color("Red", "#f44336"));
        Category category = categoryRepository.save(new Category("Chairs"));
        subCategoryRepository.save(new SubCategory("Lounge chair", category));

        UUID personGuid = UUID.randomUUID(); //TODO - Not good practise?
        UUID listingGuid = UUID.randomUUID(); //TODO - Not good practise?

        String title = "For sale";
        String description = "Two red chairs for sale.";
        int x_length_in_mm = 900;
        int y_width_in_mm = 900;
        int z_height_in_mm = 1200;
        Condition condition = Condition.Used;
        int quantity = 2;
        BigDecimal priceDKK = BigDecimal.valueOf(100.00);
        String city = "Hellerup";

        List<SubCategory> subCategories = new ArrayList<>();
        subCategories.add(new SubCategory("Lounge chair", new Category("Chairs")));

        List<Color> colors = new ArrayList<>();
        colors.add(new Color("Red", "#f44336"));

        Listing listing = new Listing(listingGuid, personGuid, title, description, x_length_in_mm, y_width_in_mm,
                z_height_in_mm, condition, quantity, priceDKK, city, subCategories, colors );

        /*Act*/
        Listing actual;
        try {
            actual = listingsService.addListing(listing);

        /*Assert*/
        Assertions.assertNotNull(actual); //returning persisted non-empty listing
        Assertions.assertNotNull(actual.getId()); //Internal ID for details is generated by not being empty
        Assertions.assertNotNull(actual.getListingDetails().getId()); //Internal ID for listing core is generated by not being empty
        Assertions.assertEquals(actual.getGuid(), listingGuid); //GUID in created listing is same as input

        } catch (CloneNotSupportedException e) {
            System.out.println("Listing is duplicated: " + e.getMessage());
        }
    }
}