
###Local properties for development

spring.application.name=product-storage

spring.security.user.name=[Type in username for login on API]
spring.security.user.password=[Type in password for login on API]

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://[Type in host]:[Type in DB port]/[Type in DB name]
spring.datasource.username=[Type in username from DB]
spring.datasource.password=[Type in password from DB]

spring.jpa.hibernate.ddl-auto=update
  ##^ possible that you have to change 'update' to 'create' while running first time - REMEMBER! change back to 'update'